### ISSUE TITLE
All "featured" articles show errant tags.

### ISSUE THREAD

**Issue by Digital-Grinnell** [McFateM/rootstalk-static#27]
The tags appear just below the article's banner image, like this example from /volume-vi-issue-1/payne/:

![Screen Shot 2020-11-10 at 9 25 57 AM](https://user-images.githubusercontent.com/15091832/98694301-e610d100-2336-11eb-8f91-7120c44fb04a.png)

The errant tags always appear to be the same.

Looking at this more closely, I'm not sure these are "errant".  It appears that the logic here is this:  If an article has a tag, any tag, then the "tags" portion is shown and that section lists ALL of the tags from ALL articles, even those tags that the article does not share. 

Is this the "correct" behavior?  I don't think so.  My inclination is that only tags that are common/shared with this article should be shown, that way the reader gets some sense of what the "related" content might be.

**Comment by McFateM** [comment]
Resolved.  The tags now look more like this:

![Screen Shot 2020-11-11 at 12 00 10 AM](https://user-images.githubusercontent.com/8472769/98774924-9f13f180-23b1-11eb-85b4-ce380f04b07d.png)
